server:
  port: ${SERVER_POT}

spring:
  application:
    name: crypto-service

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Logging Configuration
logging:
  level:
    com.sahu.cryptoservice: ${LOG_LEVEL}

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /documentation
  api-docs:
    path: /api-docs

openapi:
  title: 🚀 Spring Boot Crypto Service
  description: A Spring Boot application that provides cryptographic services including encryption, decryption, and hashing functionalities.
  version: 1.0.0
  contact:
    name: Nirmala Sahu
    email: nirmalakumarsahu7@gmail.com
    url: https://nirmalakumarsahu.in
  servers:
    - name: dev
      url: http://localhost:9897
      description: Local Development URL
